### ISSUE TITLE
 Caused by: java.lang.ClassNotFoundException: Kodein module class not found

### ISSUE THREAD

**Issue by GentleLi** [igorwojda/android-showcase#120]
com.igorwojda.showcase E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.igorwojda.showcase, PID: 9269
    java.lang.ExceptionInInitializerError
        at com.igorwojda.showcase.app.ShowcaseApplication$kodein$1.invoke(ShowcaseApplication.kt:25)
        at com.igorwojda.showcase.app.ShowcaseApplication$kodein$1.invoke(ShowcaseApplication.kt:20)
        at org.kodein.di.internal.KodeinImpl$Companion.newBuilder(KodeinImpl.kt:22)
        at org.kodein.di.internal.KodeinImpl$Companion.access$newBuilder(KodeinImpl.kt:21)
        at org.kodein.di.internal.KodeinImpl.<init>(KodeinImpl.kt:19)
        at org.kodein.di.Kodein$Companion$lazy$1.invoke(Kodein.kt:447)
        at org.kodein.di.Kodein$Companion$lazy$1.invoke(Kodein.kt:429)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.kodein.di.LazyKodein.getBaseKodein(Unknown Source:2)
        at org.kodein.di.LazyKodein.getContainer(lateinit.kt:31)
        at org.kodein.di.internal.KodeinMainBuilderImpl.extend(KodeinBuilderImpl.kt:80)
        at org.kodein.di.Kodein$MainBuilder$DefaultImpls.extend$default(Kodein.kt:384)
        at com.igorwojda.showcase.library.base.presentation.activity.InjectionActivity$kodein$2.invoke(InjectionActivity.kt:24)
        at com.igorwojda.showcase.library.base.presentation.activity.InjectionActivity$kodein$2.invoke(InjectionActivity.kt:15)
        at org.kodein.di.internal.KodeinImpl$Companion.newBuilder(KodeinImpl.kt:22)
        at org.kodein.di.internal.KodeinImpl$Companion.access$newBuilder(KodeinImpl.kt:21)
        at org.kodein.di.internal.KodeinImpl.<init>(KodeinImpl.kt:19)
        at org.kodein.di.Kodein$Companion.invoke(Kodein.kt:438)
        at org.kodein.di.android.RetainedKt$retainedKodein$1.invoke(retained.kt:34)
        at org.kodein.di.android.RetainedKt$retainedKodein$1.invoke(Unknown Source:0)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.igorwojda.showcase.library.base.presentation.activity.InjectionActivity.getKodein(Unknown Source:2)
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(KodeinAware.kt:176)
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(Unknown Source:4)
        at org.kodein.di.KodeinProperty$provideDelegate$1.invoke(properties.kt:42)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.igorwojda.showcase.app.presentation.NavHostActivity.getNavManager(Unknown Source:7)
        at com.igorwojda.showcase.app.presentation.NavHostActivity.initNavManager(NavHostActivity.kt:30)
        at com.igorwojda.showcase.app.presentation.NavHostActivity.onCreate(NavHostActivity.kt:22)
        at android.app.Activity.performCreate(Activity.java:7122)
        at android.app.Activity.performCreate(Activity.java:7113)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2965)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3090)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6866)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:817)
     Caused by: java.lang.ClassNotFoundException: Kodein module class not found com.igorwojda.showcase.feature.album.FeatureKodeinModule
        at com.igorwojda.showcase.app.feature.FeatureManager.<clinit>(FeatureManager.kt:19)
        at com.igorwojda.showcase.app.ShowcaseApplication$kodein$1.invoke(ShowcaseApplication.kt:25) 
        at com.igorwojda.showcase.app.ShowcaseApplication$kodein$1.invoke(ShowcaseApplication.kt:20) 
        at org.kodein.di.internal.KodeinImpl$Companion.newBuilder(KodeinImpl.kt:22) 
        at org.kodein.di.internal.KodeinImpl$Companion.access$newBuilder(KodeinImpl.kt:21) 
        at org.kodein.di.internal.KodeinImpl.<init>(KodeinImpl.kt:19) 
        at org.kodein.di.Kodein$Companion$lazy$1.invoke(Kodein.kt:447) 
        at org.kodein.di.Kodein$Companion$lazy$1.invoke(Kodein.kt:429) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at org.kodein.di.LazyKodein.getBaseKodein(Unknown Source:2) 
        at org.kodein.di.LazyKodein.getContainer(lateinit.kt:31) 
        at org.kodein.di.internal.KodeinMainBuilderImpl.extend(KodeinBuilderImpl.kt:80) 
        at org.kodein.di.Kodein$MainBuilder$DefaultImpls.extend$default(Kodein.kt:384) 
        at com.igorwojda.showcase.library.base.presentation.activity.InjectionActivity$kodein$2.invoke(InjectionActivity.kt:24) 
        at com.igorwojda.showcase.library.base.presentation.activity.InjectionActivity$kodein$2.invoke(InjectionActivity.kt:15) 
        at org.kodein.di.internal.KodeinImpl$Companion.newBuilder(KodeinImpl.kt:22) 
        at org.kodein.di.internal.KodeinImpl$Companion.access$newBuilder(KodeinImpl.kt:21) 
        at org.kodein.di.internal.KodeinImpl.<init>(KodeinImpl.kt:19) 
        at org.kodein.di.Kodein$Companion.invoke(Kodein.kt:438) 
        at org.kodein.di.android.RetainedKt$retainedKodein$1.invoke(retained.kt:34) 
        at org.kodein.di.android.RetainedKt$retainedKodein$1.invoke(Unknown Source:0) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at com.igorwojda.showcase.library.base.presentation.activity.InjectionActivity.getKodein(Unknown Source:2) 
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(KodeinAware.kt:176) 
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(Unknown Source:4) 
        at org.kodein.di.KodeinProperty$provideDelegate$1.invoke(properties.kt:42) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at com.igorwojda.showcase.app.presentation.NavHostActivity.getNavManager(Unknown Source:7) 
        at com.igorwojda.showcase.app.presentation.NavHostActivity.initNavManager(NavHostActivity.kt:30) 
        at com.igorwojda.showcase.app.presentation.NavHostActivity.onCreate(NavHostActivity.kt:22) 
        at android.app.Activity.performCreate(Activity.java:7122) 
        at android.app.Activity.performCreate(Activity.java:7113) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2965) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3090) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:6866) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:817)

**Comment by hike2008** [comment]
same problem

**Comment by igorwojda** [comment]
Can you try this now?

Also do you just launch the app after clean repo checkout or do something else?

**Comment by igorwojda** [comment]
Closing as the project was migrated to [koin](https://insert-koin.io/)
