### ISSUE TITLE
RuntimeException: cannot find implementation for feature.album.data.database.AlbumDatabase. AlbumDatabase_Impl does not exist

### ISSUE THREAD

**Issue by tim4dev** [igorwojda/android-showcase#181]
Build and run app:

```
2021-10-14 08:41:20.896 17168-17168/com.igorwojda.showcase D/AndroidRuntime: Shutting down VM
2021-10-14 08:41:20.899 17168-17168/com.igorwojda.showcase E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.igorwojda.showcase, PID: 17168
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.igorwojda.showcase/com.igorwojda.showcase.app.presentation.NavHostActivity}: java.lang.reflect.InvocationTargetException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.igorwojda.showcase.base.delegate.ActivityViewBindingDelegate.getValue(ActivityViewBindingDelegate.kt:20)
        at com.igorwojda.showcase.app.presentation.NavHostActivity.getBinding(NavHostActivity.kt:16)
        at com.igorwojda.showcase.app.presentation.NavHostActivity.onCreate(NavHostActivity.kt:24)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class fragment
     Caused by: java.lang.RuntimeException: cannot find implementation for com.igorwojda.showcase.feature.album.data.database.AlbumDatabase. AlbumDatabase_Impl does not exist
        at androidx.room.Room.getGeneratedImplementation(Room.java:100)
        at androidx.room.RoomDatabase$Builder.build(RoomDatabase.java:1459)
        at com.igorwojda.showcase.feature.album.data.AlbumDataModuleKt$dataModule$1$4.invoke(AlbumDataModule.kt:30)
        at com.igorwojda.showcase.feature.album.data.AlbumDataModuleKt$dataModule$1$4.invoke(AlbumDataModule.kt:30)
        at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:98)
        at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:65)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:98)
        at org.kodein.di.KodeinContainer$provider$$inlined$toProvider$1.invoke(curry.kt:14)
        at org.kodein.di.internal.DKodeinBaseImpl.Instance(DKodeinImpl.kt:30)
        at com.igorwojda.showcase.feature.album.data.AlbumDataModuleKt$dataModule$1$5.invoke(AlbumDataModule.kt:35)
        at com.igorwojda.showcase.feature.album.data.AlbumDataModuleKt$dataModule$1$5.invoke(AlbumDataModule.kt:32)
        at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:98)
        at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:65)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:98)
        at org.kodein.di.KodeinContainer$provider$$inlined$toProvider$1.invoke(curry.kt:14)
        at org.kodein.di.internal.DKodeinBaseImpl.Instance(DKodeinImpl.kt:30)
2021-10-14 08:41:20.901 17168-17168/com.igorwojda.showcase E/AndroidRuntime:     at com.igorwojda.showcase.feature.album.data.AlbumDataModuleKt$dataModule$1$1.invoke(AlbumDataModule.kt:35)
        at com.igorwojda.showcase.feature.album.data.AlbumDataModuleKt$dataModule$1$1.invoke(AlbumDataModule.kt:18)
        at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:98)
        at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:65)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:98)
        at org.kodein.di.KodeinContainer$provider$$inlined$toProvider$1.invoke(curry.kt:14)
        at org.kodein.di.internal.DKodeinBaseImpl.Instance(DKodeinImpl.kt:30)
        at com.igorwojda.showcase.feature.album.domain.AlbumDomainModuleKt$domainModule$1$1.invoke(AlbumDomainModule.kt:18)
        at com.igorwojda.showcase.feature.album.domain.AlbumDomainModuleKt$domainModule$1$1.invoke(AlbumDomainModule.kt:13)
        at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:98)
        at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:65)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:98)
        at org.kodein.di.KodeinContainer$provider$$inlined$toProvider$1.invoke(curry.kt:14)
        at org.kodein.di.internal.DKodeinBaseImpl.Instance(DKodeinImpl.kt:30)
        at com.igorwojda.showcase.feature.album.presentation.AlbumPresentationModuleKt$presentationModule$1$1$invoke$$inlined$of$1.create(KotlinViewModelProvider.kt:31)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at com.igorwojda.showcase.feature.album.presentation.AlbumPresentationModuleKt$presentationModule$1$1.invoke(AlbumPresentationModule.kt:40)
        at com.igorwojda.showcase.feature.album.presentation.AlbumPresentationModuleKt$presentationModule$1$1.invoke(AlbumPresentationModule.kt:20)
        at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:98)
        at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:65)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:98)
        at org.kodein.di.KodeinContainer$provider$$inlined$toProvider$1.invoke(curry.kt:14)
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(KodeinAware.kt:176)
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(Unknown Source:4)
        at org.kodein.di.KodeinProperty$provideDelegate$1.invoke(properties.kt:42)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.igorwojda.showcase.feature.album.presentation.albumlist.AlbumListFragment.getViewModel(AlbumListFragment.kt:20)
        at com.igorwojda.showcase.feature.album.presentation.albumlist.AlbumListFragment.onViewCreated(AlbumListFragment.kt:51)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2985)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:532)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:259)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
2021-10-14 08:41:20.902 17168-17168/com.igorwojda.showcase E/AndroidRuntime:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1327)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2757)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2693)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2986)
        at androidx.fragment.app.FragmentStateManager.ensureInflatedView(FragmentStateManager.java:375)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:258)
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:142)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:295)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:274)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.igorwojda.showcase.databinding.ActivityNavHostBinding.inflate(ActivityNavHostBinding.java:44)
        at com.igorwojda.showcase.databinding.ActivityNavHostBinding.inflate(ActivityNavHostBinding.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.igorwojda.showcase.base.delegate.ActivityViewBindingDelegate.getValue(ActivityViewBindingDelegate.kt:20)
        at com.igorwojda.showcase.app.presentation.NavHostActivity.getBinding(NavHostActivity.kt:16)
        at com.igorwojda.showcase.app.presentation.NavHostActivity.onCreate(NavHostActivity.kt:24)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Comment by igorwojda** [comment]
Thanks. for the feedback.

The project is being upgraded to version 2.0 (WiP).
I am closing this issue as it is most likely obsolete.

Feel free to report more feedback.
