### ISSUE TITLE
     Caused by: android.view.InflateException: Binary XML file line #20 in com.igorwojda.showcase:layout/activity_nav_host: Binary XML file line #20 in com.igorwojda.showcase:layout/activity_nav_host: Error inflating class fragment

### ISSUE THREAD

**Issue by BoyCoding** [igorwojda/android-showcase#182]
2021-10-23 12:01:49.977 14308-14308/? E/libc: Access denied finding property "persist.device_config.runtime_native.use_app_image_startup_cache"
        at android.os.Binder.onTransact(libmapleframework.so:3612448) 
        at android.app.IActivityManager$Stub.onTransact(libmapleframework.so:6134032) 
2021-10-23 12:01:49.977 14308-14308/? E/rwojda.showcas: LoadAppImageStartupCache enabled : 1
        at com.android.server.am.ActivityManagerService.onTransact(libmapleservices.so:7787892) 
2021-10-23 12:01:49.977 14308-14308/? E/rwojda.showcas: Unknown bits set in runtime_flags: 0x8000
        at com.android.server.am.HwActivityManagerService.onTransact(libmaplehwServices.so:2473284) 
        at android.os.Binder.execTransactInternal(libmapleframework.so:6252252) 
2021-10-23 12:01:49.977 14308-14308/? E/libc: Access denied finding property "persist.device_config.runtime_native.use_app_image_startup_cache"
2021-10-23 12:01:49.977 14308-14308/? E/rwojda.showcas: LoadAppImageStartupCache enabled : 1
2021-10-23 12:01:49.977 14308-14308/? E/rwojda.showcas: Unknown bits set in runtime_flags: 0x8000
2021-10-23 12:01:49.926 2306-2522/? E/system_server: Invalid ID 0x00000000.
2021-10-23 12:01:49.977 14308-14308/? E/libc: Access denied finding property "persist.device_config.runtime_native.use_app_image_startup_cache"
2021-10-23 12:01:49.977 14308-14308/? E/rwojda.showcas: LoadAppImageStartupCache enabled : 1
2021-10-23 12:01:49.977 14308-14308/? E/rwojda.showcas: Unknown bits set in runtime_flags: 0x8000
2021-10-23 12:01:50.376 14308-14349/com.igorwojda.showcase E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@c6e8d37
2021-10-23 12:01:50.833 14308-14308/com.igorwojda.showcase E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.igorwojda.showcase, PID: 14308
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.igorwojda.showcase/com.igorwojda.showcase.app.presentation.NavHostActivity}: java.lang.reflect.InvocationTargetException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4060)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.igorwojda.showcase.base.delegate.ActivityViewBindingDelegate.getValue(ActivityViewBindingDelegate.kt:20)
        at com.igorwojda.showcase.app.presentation.NavHostActivity.getBinding(NavHostActivity.kt:16)
        at com.igorwojda.showcase.app.presentation.NavHostActivity.onCreate(NavHostActivity.kt:24)
        at android.app.Activity.performCreate(Activity.java:8214)
        at android.app.Activity.performCreate(Activity.java:8202)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8668) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) 
     Caused by: android.view.InflateException: Binary XML file line #20 in com.igorwojda.showcase:layout/activity_nav_host: Binary XML file line #20 in com.igorwojda.showcase:layout/activity_nav_host: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #20 in com.igorwojda.showcase:layout/activity_nav_host: Error inflating class fragment
     Caused by: java.lang.RuntimeException: cannot find implementation for com.igorwojda.showcase.feature.album.data.database.AlbumDatabase. AlbumDatabase_Impl does not exist
        at androidx.room.Room.getGeneratedImplementation(Room.java:100)
        at androidx.room.RoomDatabase$Builder.build(RoomDatabase.java:1459)
        at com.igorwojda.showcase.feature.album.data.AlbumDataModuleKt$dataModule$1$4.invoke(AlbumDataModule.kt:30)
        at com.igorwojda.showcase.feature.album.data.AlbumDataModuleKt$dataModule$1$4.invoke(AlbumDataModule.kt:30)
        at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:98)
        at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:65)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:98)
        at org.kodein.di.KodeinContainer$provider$$inlined$toProvider$1.invoke(curry.kt:14)
        at org.kodein.di.internal.DKodeinBaseImpl.Instance(DKodeinImpl.kt:30)
        at com.igorwojda.showcase.feature.album.data.AlbumDataModuleKt$dataModule$1$5.invoke(AlbumDataModule.kt:35)
        at com.igorwojda.showcase.feature.album.data.AlbumDataModuleKt$dataModule$1$5.invoke(AlbumDataModule.kt:32)
        at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:98)

**Comment by tudormot** [comment]
same

**Comment by mybirthfather** [comment]
hi do you resolve this problem? i  hava same problem with you

**Comment by huangsir0** [comment]
hi do you resolve this problem? i hava same problem with you

**Comment by igorwojda** [comment]
Thanks. for the feedback. 

The project has been upgraded to version 2.0.
UI will be migrated soon, so I am closing this issue as it is most likely outdated.
