### ISSUE TITLE
please fix this project

### ISSUE THREAD

**Issue by shunlibest** [igorwojda/android-showcase#192]
When I run this project , I find some error, I need author to fix it;

1. please rename **[item_album_list.xml]** to **[fragment_album_list_item.xml]**; otherwise CAN NOT find [FragmentAlbumListItemBinding]

2. Error msg below ↓, I do not know how to fix it; 

     Caused by: android.view.InflateException: Binary XML file line #20 in com.igorwojda.showcase:layout/activity_nav_host: Binary XML file line #20 in com.igorwojda.showcase:layout/activity_nav_host: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #20 in com.igorwojda.showcase:layout/activity_nav_host: Error inflating class fragment
     Caused by: java.lang.RuntimeException: cannot find implementation for com.igorwojda.showcase.feature.album.data.database.AlbumDatabase. AlbumDatabase_Impl does not exist
        at androidx.room.Room.getGeneratedImplementation(Room.java:100)
        at androidx.room.RoomDatabase$Builder.build(RoomDatabase.java:1459)
        at com.igorwojda.showcase.feature.album.data.AlbumDataModuleKt$dataModule$1$4.invoke(AlbumDataModule.kt:30)
        at com.igorwojda.showcase.feature.album.data.AlbumDataModuleKt$dataModule$1$4.invoke(AlbumDataModule.kt:30)

**Comment by igorwojda** [comment]
Thanks. for the feedback. 

The project has been upgraded to version 2.0.
I have still some work to do, but the project should now work with the new Android Studio.
